manifestVersion: subsquid.io/v0.1
name: dapps-staking-indexer-astar
version: 13
description: "ArrowSquid Indexer for Dapps Staking V3"
build:
scale:
  dedicated: true
  processor:
    profile: medium
deploy:
  addons:
    postgres:
    rpc:
      - astar-substrate:http
  processor:
    cmd:
      - node
      - lib/main
    env:
      RPC_ENDPOINT: https://astar.api.onfinality.io/public
      BLOCK_RANGE: 4342300
      ARCHIVE: astar
      V3_FIRST_BLOCK: 5514934
      V3_PERIOD_LENGTH: 878400
      V3_FIRST_ERA: 651
      V3_ERAS_PER_PERIOD: 112
  api:
    cmd:
      - npx
      - squid-graphql-server
      - "--dumb-cache"
      - in-memory
      - "--dumb-cache-ttl"
      - "1000"
      - "--dumb-cache-size"
      - "100"
      - "--dumb-cache-max-age"
      - "1000"
