manifestVersion: subsquid.io/v0.1
name: "dapps-staking-indexer-astar"
version: 1
description: 'ArrowSquid Indexer for Dapps Staking V3'
build: 
deploy:
  addons:
    postgres: 
  processor:
    cmd:
      - node
      - lib/main
    env:
      RPC_ENDPOINT: wss://astar-rpc.dwellir.com
      BLOCK_RANGE: 4342300
  api:
    cmd:
      - npx
      - squid-graphql-server
      - '--dumb-cache'
      - in-memory
      - '--dumb-cache-ttl'
      - '1000'
      - '--dumb-cache-size'
      - '100'
      - '--dumb-cache-max-age'
      - '1000'
