manifestVersion: subsquid.io/v0.1
name: dapps-staking-indexer-astar
version: 3
description: "ArrowSquid Indexer for Dapps Staking V3"
build:
scale:
  dedicated: true
deploy:
  addons:
    postgres:
    rpc:
      - astar-substrate:http
  processor:
    cmd:
      - node
      - lib/main
    env:
      RPC_ENDPOINT: wss://rpc.astar.network
      BLOCK_RANGE: 4342300
      ARCHIVE: astar
  api:
    cmd:
      - npx
      - squid-graphql-server
      - "--dumb-cache"
      - in-memory
      - "--dumb-cache-ttl"
      - "1000"
      - "--dumb-cache-size"
      - "100"
      - "--dumb-cache-max-age"
      - "1000"
