manifestVersion: subsquid.io/v0.1
name: dapps-staking-indexer-shiden
version: 3
description: "ArrowSquid Indexer for Dapps Staking V3"
build:
scale:
  dedicated: true
deploy:
  addons:
    postgres:
    rpc:
      - shiden-substrate:http
  processor:
    cmd:
      - node
      - lib/main
    env:
      RPC_ENDPOINT: wss://shiden-rpc.dwellir.com
      BLOCK_RANGE: 5876078
      ARCHIVE: shiden
  api:
    cmd:
      - npx
      - squid-graphql-server
      - "--dumb-cache"
      - in-memory
      - "--dumb-cache-ttl"
      - "1000"
      - "--dumb-cache-size"
      - "100"
      - "--dumb-cache-max-age"
      - "1000"
